# Generated by Django 6.0.6 on 2026-06-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=255, verbose_name='Имя звонящего')),
                ('caller_phone', models.CharField(max_length=50, verbose_name='Телефон звонящего')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активный'), ('ended', 'Завершён'), ('missed', 'Пропущен')], default='waiting', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('room_id', models.CharField(max_length=100, unique=True, verbose_name='ID комнаты WebRTC')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('busy', 'Занят'), ('offline', 'Офлайн')], default='offline', max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_status', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Статус менеджера',
                'verbose_name_plural': 'Статусы менеджеров',
            },
        ),
    ]
